In [18]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# 1. Load the Excel data
df = pd.read_excel('house_data.xlsx')
df

,Square_Feet (X),Price (y)
0,500,150000
1,750,200000
2,1000,250000
3,1200,300000
4,1500,340000
5,2000,450000


In [3]:
print(df.columns)

Index(['Square_Feet (X)', 'Price (y)'], dtype='object')


In [21]:
# 2. Prepare the data
# We reshape X because the model expects a 2D array
X = df[['Square_Feet (X)']]
y = df['Price (y)']

# 3. Initialize and Train the model
model = LinearRegression()
model.fit(X,y)

# 4. Make a prediction
new_house = pd.DataFrame({'Square_Feet (X)': [1800]})
prediction = model.predict(new_house)

new_house

,Square_Feet (X)
0,1800


In [15]:
prediction

array([408674.31850789])

In [12]:
sq_ft_value = new_house.iloc[0, 0]
print(f"The predicted price for an {sq_ft_value} sq ft house is: ${prediction[0]:,.2f}")

The predicted price for an 1800 sq ft house is: $408,674.32


In [17]:
from sklearn.metrics import mean_absolute_error, r2_score

predictions = model.predict(X)

#Calculate MAE
mae = mean_absolute_error(y, predictions)
print(f"Mean Absolute Error (MAE): ${mae:,.2f}")

#Calculate R-Squared
r2 = r2_score(y, predictions)
print(f"R-Squared (R2) Score: {r2:.4f}")

Mean Absolute Error (MAE): $3,941.65
R-Squared (R2) Score: 0.9966


In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# 1. Generate 100 random houses (Square feet between 800 and 4000)
np.random.seed(42) # This ensures we both get the exact same random numbers
X_large = np.random.randint(800, 4000, size=(100, 1))

# Generate realistic prices: $150 per sq ft, plus a $50k base, plus some random "noise." 
# (because some houses are nicer than others!)
y_large = (X_large[:, 0] * 150) + 50000 + np.random.normal(0, 30000, 100)

X_large

array([[3974],
       [1660],
       [2094],
       [1930],
       [1895],
       [3892],
       [2438],
       [2969],
       [1266],
       [2038],
       [1130],
       [2282],
       [2935],
       [3971],
       [3719],
       [ 930],
       [2485],
       [1569],
       [3191],
       [2315],
       [3653],
       [3233],
       [2015],
       [1755],
       [3124],
       [1984],
       [1259],
       [ 821],
       [3100],
       [1547],
       [3704],
       [1274],
       [1882],
       [3358],
       [2847],
       [3547],
       [1775],
       [2606],
       [ 989],
       [3805],
       [3534],
       [3805],
       [1362],
       [2699],
       [2067],
       [3679],
       [2328],
       [1446],
       [2868],
       [3688],
       [3014],
       [2097],
       [3235],
       [1400],
       [3163],
       [2861],
       [1041],
       [2841],
       [3624],
       [3412],
       [3745],
       [2163],
       [2939],
       [2190],
       [3803],
       [2278],
       [33

In [24]:
y_large

array([612183.43085955, 303032.86647884, 381563.68384139, 366132.4537878 ,
       361079.96990326, 656449.93391734, 409485.02329686, 476645.67815045,
       194655.40131358, 388689.40927354, 214168.03636188, 379988.50073941,
       525641.49034102, 618703.76181633, 632893.86257691, 198396.84152987,
       391615.10370454, 283075.88764915, 557838.90601267, 421117.86391688,
       642813.0275865 , 545095.4375598 , 453418.8876088 , 285638.27584798,
       506640.84829954, 345774.07737576, 196287.48624226, 204424.74852018,
       542105.97471878, 282620.00993186, 589567.50638979, 196248.38387557,
       308622.25013906, 576011.33851314, 470685.15734865, 569243.93617881,
       331293.44994574, 475645.59958796, 206063.50610169, 630185.3868759 ,
       621255.86400649, 626016.59881864, 245021.34360666, 475043.76508322,
       352351.09451922, 590815.22827602, 437412.00860419, 258141.41987523,
       400544.7185731 , 613565.53831666, 490234.50645259, 355875.8943059 ,
       548838.08979601, 2

In [25]:
# 2. THE MAGIC SPLIT: 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X_large, y_large, test_size=0.20, random_state=42)

print(f"Training on {len(X_train)} houses...")
print(f"Testing on {len(X_test)} hidden houses...\n")

# 3. Train the model ONLY on the Training data
model_real = LinearRegression()
model_real.fit(X_train, y_train)

# 4. Test the model ONLY on the hidden Testing data
test_predictions = model_real.predict(X_test)

# 5. Grade the real-world performance
real_mae = mean_absolute_error(y_test, test_predictions)
real_r2 = r2_score(y_test, test_predictions)

print(f"REAL-WORLD MAE: ${real_mae:,.2f}")
print(f"REAL-WORLD R-Squared: {real_r2:.4f}")

Training on 80 houses...
Testing on 20 hidden houses...

REAL-WORLD MAE: $26,487.73
REAL-WORLD R-Squared: 0.9490
